MLK-21985-6 ASoC: imx-dsp: fix build for next 20190607 upgrade
API change due to:
adb76b5b9c47 ("ASoC: soc-core: remove legacy style dai_link")

../sound/soc/fsl/imx-dsp.c: In function ‘imx_dsp_audio_probe’:
../sound/soc/fsl/imx-dsp.c:123:14: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_dai_name’
  data->dai[0].codec_dai_name = "snd-soc-dummy-dai";
              ^
../sound/soc/fsl/imx-dsp.c:124:14: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_name’
  data->dai[0].codec_name = "snd-soc-dummy";
              ^
../sound/soc/fsl/imx-dsp.c:125:14: error: ‘struct snd_soc_dai_link’ has no member named ‘cpu_dai_name’
  data->dai[0].cpu_dai_name = dev_name(&cpu_pdev->dev);
              ^
../sound/soc/fsl/imx-dsp.c:126:14: error: ‘struct snd_soc_dai_link’ has no member named ‘cpu_of_node’
  data->dai[0].cpu_of_node = cpu_np;
              ^
../sound/soc/fsl/imx-dsp.c:127:14: error: ‘struct snd_soc_dai_link’ has no member named ‘platform_of_node’
  data->dai[0].platform_of_node = platform_np;
              ^
../sound/soc/fsl/imx-dsp.c:140:14: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_dai_name’
  data->dai[1].codec_dai_name = "cs42888";
              ^
../sound/soc/fsl/imx-dsp.c:141:14: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_of_node’
  data->dai[1].codec_of_node = codec_np;
              ^
../sound/soc/fsl/imx-dsp.c:142:14: error: ‘struct snd_soc_dai_link’ has no member named ‘cpu_dai_name’
  data->dai[1].cpu_dai_name = "snd-soc-dummy-dai";
              ^
../sound/soc/fsl/imx-dsp.c:143:14: error: ‘struct snd_soc_dai_link’ has no member named ‘cpu_name’
  data->dai[1].cpu_name = "snd-soc-dummy";
              ^
../sound/soc/fsl/imx-dsp.c:144:14: error: ‘struct snd_soc_dai_link’ has no member named ‘platform_name’
  data->dai[1].platform_name = "snd-soc-dummy";

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>